package constants

const (
	ResponseMsgOK                      = "ok"
	ResponseMsgCreated                 = "successfully created"
	ResponseMsgUnauthorized            = "unauthorized"
	ResponseMsgForbidden               = "this action is forbidden"
	ResponseMsgRegistered              = "successfully registered"
	ResponseMsgLogin                   = "successfully logged in"
	ResponseMsgResetPassword           = "reset password successful"
	ResponseMsgUpdated                 = "successfully updated"
	ResponseMsgDeleted                 = "successfully deleted"
	ResponseMsgRefreshCookie           = "successfully get refresh token"
	ResponseMsgErrorNotFound           = "data not found"
	ResponseMsgErrorInvalidRequest     = "invalid request, please check your request"
	ResponseMsgErrorInternalServer     = "our server encountered error, please try again later"
	ResponseMsgVerified                = "successfully verified"
	ResponseMsgEmailNotFound           = "email is not registered yet"
	ResponseMsgSendEmail               = "successfully sent email"
	ResponseMsgIncreaseQuantity        = "successfully increased"
	ResponseMsgDecreaseQuantity        = "successfully decreased"
	ResponseMsgAddedPrescriptionToCart = "successfully added prescription to cart"
	ResponseMsgForgotPasswordSuccess   = "successfully forgot password"
	ResponseMsgResetPasswordSuccess    = "successfully reset password"
	ResponseMsgChangePasswordSuccess   = "successfully change password"
	ResponseMsgCreateOrder             = "successfully create order"
	ResponseMsgGetOrder                = "successfully get orders"
)
